/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DecisionEntry {
  'id' : number,
  'decision' : DecisionType,
  'repeatInterval' : RepeatInterval,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'lastUpdated' : Time,
  'completionFiles' : [] | [Array<ExternalBlob>],
  'isDone' : boolean,
  'comment' : [] | [string],
  'completionComment' : [] | [string],
  'timestamp' : Time,
  'decisionFiles' : [] | [Array<ExternalBlob>],
  'completionTimestamp' : [] | [Time],
}
export type DecisionType = { 'valid' : null } |
  { 'invalid' : null } |
  { 'critical' : null };
export interface DentalAvatar { 'id' : number, 'svg' : string, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface OvertimeEntry {
  'id' : number,
  'date' : Time,
  'approvedBy' : [] | [Principal],
  'createdBy' : Principal,
  'minutes' : bigint,
  'approved' : boolean,
}
export type ProfileRole = { 'manager' : null } |
  { 'assistant' : null };
export type RepeatInterval = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface Task {
  'id' : number,
  'title' : string,
  'lastResetAt' : Time,
  'nextResetTimestamp' : [] | [Time],
  'isCompleted' : boolean,
  'description' : string,
  'taskType' : TaskType,
  'currentCompletion' : [] | [TaskCompletion],
}
export interface TaskCompletion {
  'completedAt' : Time,
  'completedBy' : Principal,
  'afterPhoto' : [] | [ExternalBlob],
  'beforePhoto' : [] | [ExternalBlob],
  'comment' : [] | [string],
}
export type TaskType = { 'urgent' : null } |
  { 'monthly' : null } |
  { 'weekly' : null };
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'role' : ProfileRole,
  'initials' : string,
  'avatar' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<
    [number, [] | [string], [] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
  'createOvertimeEntry' : ActorMethod<[bigint, Time], OvertimeEntry>,
  'createTask' : ActorMethod<[string, string, TaskType], undefined>,
  'editTask' : ActorMethod<[number, string, string, TaskType], undefined>,
  'exportTaskData' : ActorMethod<[], Array<Task>>,
  'getAllDentalAvatars' : ActorMethod<[], Array<DentalAvatar>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerOvertimeEntries' : ActorMethod<[], Array<OvertimeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDecisionEntries' : ActorMethod<[], Array<DecisionEntry>>,
  'getProfilePhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserOvertimeEntries' : ActorMethod<[Principal], Array<OvertimeEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeProfilePhoto' : ActorMethod<[], undefined>,
  'resetRecurringTasksIfNeeded' : ActorMethod<[], undefined>,
  'resetTask' : ActorMethod<[number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectRoleAssistant' : ActorMethod<[], undefined>,
  'selectRoleManager' : ActorMethod<[string], undefined>,
  'uploadProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];