/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const OvertimeEntry = IDL.Record({
  'id' : IDL.Nat32,
  'date' : Time,
  'approvedBy' : IDL.Opt(IDL.Principal),
  'createdBy' : IDL.Principal,
  'minutes' : IDL.Int,
  'approved' : IDL.Bool,
});
export const TaskType = IDL.Variant({
  'urgent' : IDL.Null,
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const TaskCompletion = IDL.Record({
  'completedAt' : Time,
  'completedBy' : IDL.Principal,
  'afterPhoto' : IDL.Opt(ExternalBlob),
  'beforePhoto' : IDL.Opt(ExternalBlob),
  'comment' : IDL.Opt(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'lastResetAt' : Time,
  'nextResetTimestamp' : IDL.Opt(Time),
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'taskType' : TaskType,
  'currentCompletion' : IDL.Opt(TaskCompletion),
});
export const DentalAvatar = IDL.Record({
  'id' : IDL.Nat32,
  'svg' : IDL.Text,
  'name' : IDL.Text,
});
export const ProfileRole = IDL.Variant({
  'manager' : IDL.Null,
  'assistant' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'role' : ProfileRole,
  'initials' : IDL.Text,
  'avatar' : IDL.Nat32,
});
export const DecisionType = IDL.Variant({
  'valid' : IDL.Null,
  'invalid' : IDL.Null,
  'critical' : IDL.Null,
});
export const RepeatInterval = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const DecisionEntry = IDL.Record({
  'id' : IDL.Nat32,
  'decision' : DecisionType,
  'repeatInterval' : RepeatInterval,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'lastUpdated' : Time,
  'completionFiles' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'isDone' : IDL.Bool,
  'comment' : IDL.Opt(IDL.Text),
  'completionComment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'decisionFiles' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'completionTimestamp' : IDL.Opt(Time),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func(
      [
        IDL.Nat32,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'createOvertimeEntry' : IDL.Func([IDL.Int, Time], [OvertimeEntry], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, TaskType], [], []),
  'exportTaskData' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllDentalAvatars' : IDL.Func([], [IDL.Vec(DentalAvatar)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerOvertimeEntries' : IDL.Func(
      [],
      [IDL.Vec(OvertimeEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDecisionEntries' : IDL.Func([], [IDL.Vec(DecisionEntry)], ['query']),
  'getProfilePhoto' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserOvertimeEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OvertimeEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeProfilePhoto' : IDL.Func([], [], []),
  'resetRecurringTasksIfNeeded' : IDL.Func([], [], []),
  'resetTask' : IDL.Func([IDL.Nat32], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectRoleAssistant' : IDL.Func([], [], []),
  'selectRoleManager' : IDL.Func([IDL.Text], [], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const OvertimeEntry = IDL.Record({
    'id' : IDL.Nat32,
    'date' : Time,
    'approvedBy' : IDL.Opt(IDL.Principal),
    'createdBy' : IDL.Principal,
    'minutes' : IDL.Int,
    'approved' : IDL.Bool,
  });
  const TaskType = IDL.Variant({
    'urgent' : IDL.Null,
    'monthly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const TaskCompletion = IDL.Record({
    'completedAt' : Time,
    'completedBy' : IDL.Principal,
    'afterPhoto' : IDL.Opt(ExternalBlob),
    'beforePhoto' : IDL.Opt(ExternalBlob),
    'comment' : IDL.Opt(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'lastResetAt' : Time,
    'nextResetTimestamp' : IDL.Opt(Time),
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'taskType' : TaskType,
    'currentCompletion' : IDL.Opt(TaskCompletion),
  });
  const DentalAvatar = IDL.Record({
    'id' : IDL.Nat32,
    'svg' : IDL.Text,
    'name' : IDL.Text,
  });
  const ProfileRole = IDL.Variant({
    'manager' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'role' : ProfileRole,
    'initials' : IDL.Text,
    'avatar' : IDL.Nat32,
  });
  const DecisionType = IDL.Variant({
    'valid' : IDL.Null,
    'invalid' : IDL.Null,
    'critical' : IDL.Null,
  });
  const RepeatInterval = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const DecisionEntry = IDL.Record({
    'id' : IDL.Nat32,
    'decision' : DecisionType,
    'repeatInterval' : RepeatInterval,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'lastUpdated' : Time,
    'completionFiles' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'isDone' : IDL.Bool,
    'comment' : IDL.Opt(IDL.Text),
    'completionComment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'decisionFiles' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'completionTimestamp' : IDL.Opt(Time),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func(
        [
          IDL.Nat32,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'createOvertimeEntry' : IDL.Func([IDL.Int, Time], [OvertimeEntry], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, TaskType], [], []),
    'exportTaskData' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllDentalAvatars' : IDL.Func([], [IDL.Vec(DentalAvatar)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerOvertimeEntries' : IDL.Func(
        [],
        [IDL.Vec(OvertimeEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDecisionEntries' : IDL.Func([], [IDL.Vec(DecisionEntry)], ['query']),
    'getProfilePhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserOvertimeEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OvertimeEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeProfilePhoto' : IDL.Func([], [], []),
    'resetRecurringTasksIfNeeded' : IDL.Func([], [], []),
    'resetTask' : IDL.Func([IDL.Nat32], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectRoleAssistant' : IDL.Func([], [], []),
    'selectRoleManager' : IDL.Func([IDL.Text], [], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };