/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface TaskCompletion {
    completedAt: Time;
    completedBy: Principal;
    afterPhoto?: ExternalBlob;
    beforePhoto?: ExternalBlob;
    comment?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OvertimeEntry {
    id: number;
    date: Time;
    approvedBy?: Principal;
    createdBy: Principal;
    minutes: bigint;
    approved: boolean;
}
export interface Task {
    id: number;
    title: string;
    lastResetAt: Time;
    nextResetTimestamp?: Time;
    isCompleted: boolean;
    description: string;
    taskType: TaskType;
    currentCompletion?: TaskCompletion;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DecisionEntry {
    id: number;
    decision: DecisionType;
    repeatInterval: RepeatInterval;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    lastUpdated: Time;
    completionFiles?: Array<ExternalBlob>;
    isDone: boolean;
    comment?: string;
    completionComment?: string;
    timestamp: Time;
    decisionFiles?: Array<ExternalBlob>;
    completionTimestamp?: Time;
}
export interface DentalAvatar {
    id: number;
    svg: string;
    name: string;
}
export interface UserProfile {
    username: string;
    profilePhoto?: ExternalBlob;
    role: ProfileRole;
    initials: string;
    avatar: number;
}
export enum DecisionType {
    valid = "valid",
    invalid = "invalid",
    critical = "critical"
}
export enum ProfileRole {
    manager = "manager",
    assistant = "assistant"
}
export enum RepeatInterval {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum TaskType {
    urgent = "urgent",
    monthly = "monthly",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTask(taskId: number, comment: string | null, beforePhoto: ExternalBlob | null, afterPhoto: ExternalBlob | null): Promise<void>;
    createOvertimeEntry(minutes: bigint, date: Time): Promise<OvertimeEntry>;
    createTask(title: string, description: string, taskType: TaskType): Promise<void>;
    editTask(taskId: number, newTitle: string, newDescription: string, newTaskType: TaskType): Promise<void>;
    exportTaskData(): Promise<Array<Task>>;
    getAllDentalAvatars(): Promise<Array<DentalAvatar>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerOvertimeEntries(): Promise<Array<OvertimeEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDecisionEntries(): Promise<Array<DecisionEntry>>;
    getProfilePhoto(user: Principal): Promise<ExternalBlob | null>;
    getTasks(): Promise<Array<Task>>;
    getUserOvertimeEntries(user: Principal): Promise<Array<OvertimeEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeProfilePhoto(): Promise<void>;
    resetRecurringTasksIfNeeded(): Promise<void>;
    resetTask(taskId: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectRoleAssistant(): Promise<void>;
    selectRoleManager(_token: string): Promise<void>;
    uploadProfilePhoto(photo: ExternalBlob): Promise<void>;
}
import type { DecisionEntry as _DecisionEntry, DecisionType as _DecisionType, ExternalBlob as _ExternalBlob, OvertimeEntry as _OvertimeEntry, ProfileRole as _ProfileRole, RepeatInterval as _RepeatInterval, Task as _Task, TaskCompletion as _TaskCompletion, TaskType as _TaskType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: number, arg1: string | null, arg2: ExternalBlob | null, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createOvertimeEntry(arg0: bigint, arg1: Time): Promise<OvertimeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createOvertimeEntry(arg0, arg1);
                return from_candid_OvertimeEntry_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOvertimeEntry(arg0, arg1);
            return from_candid_OvertimeEntry_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: string, arg1: string, arg2: TaskType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_TaskType_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_TaskType_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async editTask(arg0: number, arg1: string, arg2: string, arg3: TaskType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTask(arg0, arg1, arg2, to_candid_TaskType_n16(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTask(arg0, arg1, arg2, to_candid_TaskType_n16(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async exportTaskData(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportTaskData();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportTaskData();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDentalAvatars(): Promise<Array<DentalAvatar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDentalAvatars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDentalAvatars();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerOvertimeEntries(): Promise<Array<OvertimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerOvertimeEntries();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerOvertimeEntries();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDecisionEntries(): Promise<Array<DecisionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecisionEntries();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecisionEntries();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfilePhoto(arg0: Principal): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilePhoto(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilePhoto(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOvertimeEntries(arg0: Principal): Promise<Array<OvertimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOvertimeEntries(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOvertimeEntries(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeProfilePhoto(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfilePhoto();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfilePhoto();
            return result;
        }
    }
    async resetRecurringTasksIfNeeded(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetRecurringTasksIfNeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetRecurringTasksIfNeeded();
            return result;
        }
    }
    async resetTask(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTask(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selectRoleAssistant(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectRoleAssistant();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectRoleAssistant();
            return result;
        }
    }
    async selectRoleManager(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectRoleManager(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectRoleManager(arg0);
            return result;
        }
    }
    async uploadProfilePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_DecisionEntry_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DecisionEntry): Promise<DecisionEntry> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_DecisionType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DecisionType): DecisionType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OvertimeEntry_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OvertimeEntry): OvertimeEntry {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRole): ProfileRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_RepeatInterval_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepeatInterval): RepeatInterval {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_TaskCompletion_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskCompletion): Promise<TaskCompletion> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Promise<Task> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskCompletion]): Promise<TaskCompletion | null> {
    return value.length === 0 ? null : await from_candid_TaskCompletion_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalBlob>]): Promise<Array<ExternalBlob> | null> {
    return value.length === 0 ? null : await from_candid_vec_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    date: _Time;
    approvedBy: [] | [Principal];
    createdBy: Principal;
    minutes: bigint;
    approved: boolean;
}): {
    id: number;
    date: Time;
    approvedBy?: Principal;
    createdBy: Principal;
    minutes: bigint;
    approved: boolean;
} {
    return {
        id: value.id,
        date: value.date,
        approvedBy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.approvedBy)),
        createdBy: value.createdBy,
        minutes: value.minutes,
        approved: value.approved
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    title: string;
    lastResetAt: _Time;
    nextResetTimestamp: [] | [_Time];
    isCompleted: boolean;
    description: string;
    taskType: _TaskType;
    currentCompletion: [] | [_TaskCompletion];
}): Promise<{
    id: number;
    title: string;
    lastResetAt: Time;
    nextResetTimestamp?: Time;
    isCompleted: boolean;
    description: string;
    taskType: TaskType;
    currentCompletion?: TaskCompletion;
}> {
    return {
        id: value.id,
        title: value.title,
        lastResetAt: value.lastResetAt,
        nextResetTimestamp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.nextResetTimestamp)),
        isCompleted: value.isCompleted,
        description: value.description,
        taskType: from_candid_TaskType_n22(_uploadFile, _downloadFile, value.taskType),
        currentCompletion: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.currentCompletion))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Time;
    completedBy: Principal;
    afterPhoto: [] | [_ExternalBlob];
    beforePhoto: [] | [_ExternalBlob];
    comment: [] | [string];
}): Promise<{
    completedAt: Time;
    completedBy: Principal;
    afterPhoto?: ExternalBlob;
    beforePhoto?: ExternalBlob;
    comment?: string;
}> {
    return {
        completedAt: value.completedAt,
        completedBy: value.completedBy,
        afterPhoto: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.afterPhoto)),
        beforePhoto: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.beforePhoto)),
        comment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.comment))
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    profilePhoto: [] | [_ExternalBlob];
    role: _ProfileRole;
    initials: string;
    avatar: number;
}): Promise<{
    username: string;
    profilePhoto?: ExternalBlob;
    role: ProfileRole;
    initials: string;
    avatar: number;
}> {
    return {
        username: value.username,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.profilePhoto)),
        role: from_candid_ProfileRole_n34(_uploadFile, _downloadFile, value.role),
        initials: value.initials,
        avatar: value.avatar
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    decision: _DecisionType;
    repeatInterval: _RepeatInterval;
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    lastUpdated: _Time;
    completionFiles: [] | [Array<_ExternalBlob>];
    isDone: boolean;
    comment: [] | [string];
    completionComment: [] | [string];
    timestamp: _Time;
    decisionFiles: [] | [Array<_ExternalBlob>];
    completionTimestamp: [] | [_Time];
}): Promise<{
    id: number;
    decision: DecisionType;
    repeatInterval: RepeatInterval;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    lastUpdated: Time;
    completionFiles?: Array<ExternalBlob>;
    isDone: boolean;
    comment?: string;
    completionComment?: string;
    timestamp: Time;
    decisionFiles?: Array<ExternalBlob>;
    completionTimestamp?: Time;
}> {
    return {
        id: value.id,
        decision: from_candid_DecisionType_n43(_uploadFile, _downloadFile, value.decision),
        repeatInterval: from_candid_RepeatInterval_n45(_uploadFile, _downloadFile, value.repeatInterval),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        lastUpdated: value.lastUpdated,
        completionFiles: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.completionFiles)),
        isDone: value.isDone,
        comment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.comment)),
        completionComment: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.completionComment)),
        timestamp: value.timestamp,
        decisionFiles: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.decisionFiles)),
        completionTimestamp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.completionTimestamp))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): Promise<[Principal, UserProfile]> {
    return [
        value[0],
        await from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgent: null;
} | {
    monthly: null;
} | {
    weekly: null;
}): TaskType {
    return "urgent" in value ? TaskType.urgent : "monthly" in value ? TaskType.monthly : "weekly" in value ? TaskType.weekly : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    assistant: null;
}): ProfileRole {
    return "manager" in value ? ProfileRole.manager : "assistant" in value ? ProfileRole.assistant : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: null;
} | {
    invalid: null;
} | {
    critical: null;
}): DecisionType {
    return "valid" in value ? DecisionType.valid : "invalid" in value ? DecisionType.invalid : "critical" in value ? DecisionType.critical : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): RepeatInterval {
    return "monthly" in value ? RepeatInterval.monthly : "daily" in value ? RepeatInterval.daily : "weekly" in value ? RepeatInterval.weekly : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Promise<Array<Task>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Task_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Promise<Array<[Principal, UserProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n31(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OvertimeEntry>): Array<OvertimeEntry> {
    return value.map((x)=>from_candid_OvertimeEntry_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DecisionEntry>): Promise<Array<DecisionEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DecisionEntry_n41(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProfileRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): _ProfileRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    profilePhoto?: ExternalBlob;
    role: ProfileRole;
    initials: string;
    avatar: number;
}): Promise<{
    username: string;
    profilePhoto: [] | [_ExternalBlob];
    role: _ProfileRole;
    initials: string;
    avatar: number;
}> {
    return {
        username: value.username,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        role: to_candid_ProfileRole_n51(_uploadFile, _downloadFile, value.role),
        initials: value.initials,
        avatar: value.avatar
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    urgent: null;
} | {
    monthly: null;
} | {
    weekly: null;
} {
    return value == TaskType.urgent ? {
        urgent: null
    } : value == TaskType.monthly ? {
        monthly: null
    } : value == TaskType.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): {
    manager: null;
} | {
    assistant: null;
} {
    return value == ProfileRole.manager ? {
        manager: null
    } : value == ProfileRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
